spring:
  application:
    name: banking-system

  datasource:
    url: jdbc:mysql://localhost:3306/banking_management
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

    database-platform: org.hibernate.dialect.MySQLDialect

#serverport
server:
  port: 8080

#Spring actuator to monitor application
management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: ThisIsMyVerySecureSecretKeyForBankingApplicationJWT2026AndItMustBeLongEnough
  expiration: 86400000